- name: Build dwm
  community.general.make:
    chdir: "{{ dotfiles_repo }}/suckless/dwm-6.3"
    target: install
  become: true
- name: Build dmenu
  community.general.make:
    chdir: "{{ dotfiles_repo }}/suckless/dmenu-5.1"
    target: install
  become: true
- name: Build st
  community.general.make:
    chdir: "{{ dotfiles_repo }}/suckless/st-0.8.5"
    target: install
  become: true
