- name: Ensure general packages are installed.
  ansible.builtin.package: 
    name: "{{ item }}"
    state: present
  loop: "{{ general_packages }}"

- name: Ensure dwm_bar_dep packages are installed.
  ansible.builtin.package: 
    name: "{{ item }}"
    state: present
  loop: "{{ dwm_bar_packages }}"
