- name: Ensure general packages are installed.
  ansible.builtin.package: 
    name: "{{ item }}"
    state: present
  loop: "{{ general_packages }}"


# Only ensure when host is arch linux
- name: Ensure dwm_bar_dep packages are installed.
  ansible.builtin.package: 
    name: "{{ item }}"
    state: present
    when:
      - ansible_distribution == "Archlinux"
  loop: "{{ dwm_bar_packages }}"
