
general_packages:
  - feh
  - picom
  - dbus
  - neovim
  - vim
  - cmake
  - gcc

dwm_bar_packages:
  - alsa-utils
  - cmus
  - xorg-setxkbmap
  - extra/mpc
  - wpa_supplicant
  - networkmanager
  - networkmanager-openvpn
  - calcurse
  - transmission-remote-gtk
  - xorg-xbacklight
  - connman
  - curl
  - pamixer
  - spotifyd
  - playerctl
  - xorg-xsetroot


dotfiles_repo: "{{ ansible_env.HOME }}/dotfiles"

